name: nicolelulu
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  fish_redux: ^0.3.1
  dio: ^3.0.9
  intl: ^0.16.1
  flutter_staggered_grid_view: ^0.3.0
  cached_network_image: ^2.0.0
  flutter_easyrefresh: ^2.1.0
  connectivity: ^0.4.8+2
  flutter_swiper: ^1.1.6
  flutter_screenutil: ^1.1.0
  shared_preferences: ^0.5.3+4
  video_player: 0.10.1+3
  fsuper: ^0.1.5
  circular_check_box: ^1.0.1
  provider: ^4.0.4
  fluro: ^1.6.3
  rxdart: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/

