import 'package:nicolelulu/generated/json/base/json_convert_content.dart';
import 'package:nicolelulu/generated/json/base/json_filed.dart';

class ModelObj with JsonConvert<ModelObj> {
  @JSONField(name: "A1")
  String a1;
  @JSONField(name: "A2")
  String a2;
  @JSONField(name: "N")
  String n;
  @JSONField(name: "M")
  String m;
  @JSONField(name: "S")
  String s;
  @JSONField(name: "C")
  String c;
  @JSONField(name: "FS")
  String fS;
  @JSONField(name: "P")
  double p;
  @JSONField(name: "NV")
  double nV;
  @JSONField(name: "Time")
  String time;
  @JSONField(name: "Tick")
  int tick;
  @JSONField(name: "B1")
  double b1;
  @JSONField(name: "B2")
  double b2;
  @JSONField(name: "B3")
  double b3;
  @JSONField(name: "B4")
  double b4;
  @JSONField(name: "B5")
  double b5;
  @JSONField(name: "B1V")
  int b1V;
  @JSONField(name: "B2V")
  int b2V;
  @JSONField(name: "B3V")
  int b3V;
  @JSONField(name: "B4V")
  int b4V;
  @JSONField(name: "B5V")
  int b5V;
  @JSONField(name: "S1")
  double s1;
  @JSONField(name: "S2")
  double s2;
  @JSONField(name: "S3")
  double s3;
  @JSONField(name: "S4")
  double s4;
  @JSONField(name: "S5")
  double s5;
  @JSONField(name: "S1V")
  int s1V;
  @JSONField(name: "S2V")
  int s2V;
  @JSONField(name: "S3V")
  int s3V;
  @JSONField(name: "S4V")
  int s4V;
  @JSONField(name: "S5V")
  int s5V;
  @JSONField(name: "ZT")
  double zT;
  @JSONField(name: "DT")
  double dT;
  @JSONField(name: "O")
  double o;
  @JSONField(name: "H")
  double h;
  @JSONField(name: "L")
  double l;
  @JSONField(name: "YC")
  double yC;
  @JSONField(name: "A")
  double a;
  @JSONField(name: "V")
  double v;
  @JSONField(name: "OV")
  int oV;
  @JSONField(name: "IV")
  int iV;
  @JSONField(name: "SY")
  int sY;
  @JSONField(name: "SJ")
  int sJ;
  @JSONField(name: "HS")
  int hS;
  @JSONField(name: "ZS")
  double zS;
  @JSONField(name: "LS")
  double lS;
  @JSONField(name: "Z")
  double z;
  @JSONField(name: "Z2")
  double z2;
  @JSONField(name: "VF")
  double vF;
  @JSONField(name: "ZF")
  double zF;
  @JSONField(name: "JS")
  int jS;
  @JSONField(name: "YJS")
  int yJS;
  @JSONField(name: "HD")
  int hD;
  @JSONField(name: "YHD")
  int yHD;
  @JSONField(name: "AVP")
  int aVP;
  @JSONField(name: "SY2")
  int sY2;
  @JSONField(name: "QJ")
  int qJ;
  @JSONField(name: "N2")
  String n2;
  @JSONField(name: "QR")
  String qR;
}
